kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{include "addressing-ref-storage-class.name" .}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{include "addressing-ref-pv.name" .}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
  labels:
    {{- include "addressing-ref-pv.labels" . | nindent 4 }}
  finalizers: [ ]
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{include "addressing-ref-storage-class.name" .}}
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.nfs.fileSystemId }}.efs.{{ .Values.global.awsRegion }}.amazonaws.com
    volumeAttributes:
      path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{include "addressing-ref-pvc.name" .}}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
  finalizers: [ ]
  labels:
    {{- include "addressing-ref-pvc.labels" . | nindent 4 }}
spec:
  storageClassName:  {{include "addressing-ref-storage-class.name" .}}
  volumeName: {{include "addressing-ref-pv.name" .}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100G