{{- if .Values.enabled }}
{{- $top := . -}}
{{- range $.Values.global.countries }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autocomplete-svc.fullname" (list $top .) }}
  labels:
    {{- include "autocomplete-svc.labels" (list $top .) | nindent 4 }}
spec:
  {{- if not $top.Values.autoscaling.enabled }}
  replicas: {{ $top.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "autocomplete-svc.selectorLabels" (list $top .) | nindent 6 }}
  template:
    metadata:
      {{- with $top.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "autocomplete-svc.selectorLabels" (list $top .) | nindent 8 }}
    spec:
      {{- with $top.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "autocomplete-svc.serviceAccountName" (list $top .) }}
      securityContext:
        {{- toYaml $top.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $top.Chart.Name }}
          securityContext:
            {{- toYaml $top.Values.securityContext | nindent 12 }}
          image: "{{ $top.Values.global.addressingImage.repository }}:{{ $top.Values.global.addressingImage.tag | default $top.Chart.AppVersion }}"
          imagePullPolicy: {{ $top.Values.global.addressingImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            {{- (include "common-svc.configuration" (list $top.Values.countryConfigurations . "resources")) | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "autocomplete-svc.volumeMounts" $top | nindent 12 }}
          env:
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ $top.Values.dataVintage.configMap.name }}
                  key: {{ (printf "autocomplete.%s.vintage" .) }}
            - name: ENABLED_ENDPOINTS
              value: autocomplete
            - name: DATA_REGION
              value: {{ . | upper }}
            - name: BLOCK_DISPATCHER_POOL_SIZE
              value: {{ include "common-svc.configuration" (list $top.Values.countryConfigurations . "blockDispatcherPoolSize") | quote }}
            - name: RESPONSE_DISPATCHER_MIN_THREADS
              value: {{ include "common-svc.configuration" (list $top.Values.countryConfigurations . "responseDispatcherMinThreads") | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: -Xverify:none -XX:TieredStopAtLevel=1 -javaagent:/opt/addressing-service/opentelemetry-javaagent-1.27.0.jar
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ $top.Values.global.otelExporterEndpoint }}
      {{- with ((get $top.Values.countryConfigurations .) | default ($top.Values.global)).nodeSelector }}
      nodeSelector:
        {{- include "common-svc.global" (list $top.Values . "nodeSelector") | nindent 8 }}
      {{- end }}
      {{- with $top.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: geoaddressing-host-volume
          persistentVolumeClaim:
            claimName: {{ include "common-svc-pvc.name" $top }}
{{- end }}
{{- end }}
