{{- if .Values.enabled }}
{{- $top := . -}}
{{- range $.Values.global.countries }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reverse-svc.fullname" (list $top .) }}
  labels:
    {{- include "reverse-svc.labels" (list $top .) | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
spec:
  type: {{ $top.Values.service.type }}
  ports:
    - port: {{ $top.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "reverse-svc.selectorLabels" (list $top .) | nindent 4 }}
{{- end }}
{{- end }}
