---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "common-svc-storage-class.name" . }}
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common-svc-pv.name" . }}
  finalizers: [ ]
  labels:
    {{- include "common-svc-pvc.labels" . | nindent 4 }}
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ include "common-svc-storage-class.name" . }}
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.efs.fileSystemId }}.efs.{{ .Values.global.awsRegion }}.amazonaws.com
    volumeAttributes:
      path: /
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common-svc-pvc.name" . }}
  finalizers: [ ]
  labels:
    {{- include "common-svc-pvc.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "common-svc-storage-class.name" . }}
  volumeName: {{ include "common-svc-pv.name" . }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100G