controller:
  replicaCount: 3
  nodeSelector:
    node-app: geo-addressing-ingress
  autoscaling:
    enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 600Mi
    limits:
      memory: 1Gi
  metrics:
    enabled: true
    port: 10254
  service:
    externalTrafficPolicy: Cluster
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      prometheus.io/scrape: "true"
      prometheus.io/port: "10254"
  config:
    use-forwarded-headers: "true"
    proxy-buffer-size: "128k"
    proxy-body-size: "10m"
