{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-emitter.secret" . }}
  labels:
    {{- include "event-emitter.labels" . | nindent 4 }}
data:
  dis_user_access_key: {{ required "DIS User Access Key and Secret should be non-empty when 'geo-addressing.event-emitter.enabled=true'. Follow https://help.precisely.com/r/Precisely-Data-Integrity-Suite/Latest/en-US/Data-Integrity-Suite/Account/API-Keys for more information!" .Values.configuration.USER_KEY | b64enc }}
  dis_user_secret: {{ required "DIS User Access Key and Secret should be non-empty when 'geo-addressing.event-emitter.enabled=true'. Follow https://help.precisely.com/r/Precisely-Data-Integrity-Suite/Latest/en-US/Data-Integrity-Suite/Account/API-Keys for more information!" .Values.configuration.USER_SECRET | b64enc }}
{{- end}}
