{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "event-emitter.secret" . }}
  labels:
    {{- include "event-emitter.labels" . | nindent 4 }}
data:
  dis_user_access_key: {{ .Values.configuration.USER_KEY | b64enc }}
  dis_user_secret: {{ .Values.configuration.USER_SECRET | b64enc }}
{{- end}}
