{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-emitter.fullname" . }}
  labels:
    {{- include "event-emitter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /prometheus
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "event-emitter.selectorLabels" . | nindent 4 }}
{{- end }}
