dataDownload:
  enabled: true
  image:
    repository: pdx-s3-extractor
    pullPolicy: Always
    tag: latest
    pullSecrets: [ ]

nameOverride: "addressing-data"
fullnameOverride: "addressing-data"

service:
  type: ClusterIP
  port: 80

nodeSelector: { }

global:
  pdxApiKey: "pdx-api-key"
  pdxSecret: "pdx-api-secret"
  mountBasePath: "/mnt/data/geoaddressing-data"
  awsRegion: "us-east-1"
  countries:
    - usa
    - aus
    - can
    - gbr
    - nzl
  efs:
    fileSystemId: fileSystemId
  dataConfigMap: "{\"verify-geocode\":{\"usa\":[\"Geocoding MLD US#United States#All USA#Spectrum Platform Data\",\"Geocoding NT Street US#United States#All USA#Spectrum Platform Data\"],\"aus\":[\"Geocoding PSMA Street#Australia#All AUS#Geocoding\",\"Geocoding GNAF Address Point#Australia#All AUS#Geocoding\"],\"can\":[\"Geocoding MLD#Canada#All CAN#Geocoding\",\"Geocoding TT Street#Canada#All CAN#Geocoding\"],\"gbr\":[\"Geocoding TT Street#United Kingdom#All GBR#Geocoding\",\"Geocoding OS Codepoint With PAF#United Kingdom#All GBR#Geocoding\"],\"nzl\":[\"Geocoding TT Street#New Zealand#All NZL#Geocoding\",\"Geocoding CR Street#New Zealand#All NZL#Geocoding\",\"Geocoding CR Address Point#New Zealand#All NZL#Geocoding\"]},\"lookup\":{\"usa\":[\"Geocoding Reverse PRECISELYID#United States#All USA#Spectrum Platform Data\",\"Geocoding MLD US#United States#All USA#Spectrum Platform Data\",\"Geocoding TT Street US#United States#All USA#Spectrum Platform Data\"],\"aus\":[\"Geocoding PSMA Street#Australia#All AUS#Geocoding\",\"Geocoding GNAF Address Point#Australia#All AUS#Geocoding\"]},\"autocomplete\":{\"usa\":[\"Predictive Addressing Points#United States#All USA#Interactive\"],\"aus\":[\"Predictive Addressing Points#Australia#All AUS#Interactive\"],\"can\":[\"Address Autocomplete Data MLD#Canada#All CAN#Interactive\"],\"nzl\":[\"Geocoding CR Address Point#New Zealand#All NZL#Geocoding\"]}}"

volumes:
  - name: geoaddressing-host-volume
    persistentVolumeClaim:
      claimName: addressing-data-pvc