replicaCount: 1

enabled: ~

imagePullSecrets: [ ]
nameOverride: "autocomplete"
fullnameOverride: "autocomplete"

serviceAccount:
  create: true
  annotations: { }
  name: ""

podAnnotations: { }
podSecurityContext: { }
securityContext: { }

# container level lifecycle hooks
containerLifecycleHooks: {}

# This is the max unavailable setting for the pod disruption budget
# The default value of 1 will make sure that kubernetes won't allow more than 1
# of your pods to be unavailable during maintenance
maxUnavailable: 1

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: { }
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: [ ]

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

tolerations: [ ]
affinity: { }