apiVersion: v2
name: geo-addressing-aks
description: A Helm chart for Geo Addressing service

type: application
version: 2.0.0
appVersion: "1.16.0"
dependencies:
  - name: geo-addressing
    repository: file://../../component-charts/geo-addressing-generic
    version: "2.0.0"