## Global configurations will be applicable and referred in every dependent helm chart
## - for more information on global parameter of helm, refer to:
##    https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
global:

  ## Configurations related to Network File System
  nfs:
    ##
    ## The Azure Storage Name
    shareName: geoaddressingshare
    ##
    ## The Azure Storage Account ID
    storageAccount: geoaddressing

geo-addressing:
  addressing-svc:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      targetCPUUtilizationPercentage: 70
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
  enabled: true
  addressing-express:
    enabled: true
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
    expressEngineData:
      memLock:
        enabled: false
      sysctlInit:
        enabled: true
      autoscaling:
        enabled: true
        minReplicas: 1
        maxReplicas: 2
        targetCPUUtilizationPercentage: 50
      resources:
        requests:
          cpu: 4
          memory: 16Gi
    expressEngineMaster:
      replicas: 1
      memLock:
        enabled: false
      sysctlInit:
        enabled: true
