version: "3.9"
services:
  precisely-regional-addressing:
    image: ${_REGIONAL_IMAGE:-regional-addressing-service:latest}
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1500M
    ports:
      - "${_SERVICE_PORT:-8080}:8080"
    environment:
      - ADDRESSING_BASE_URL=http://precisely-addressing-svc:8080
      - LOOKUP_BASE_URL=http://precisely-addressing-svc:8080
      - AUTOCOMPLETE_BASE_URL=http://precisely-addressing-svc:8080
      - REVERSE_GEOCODE_BASE_URL=http://precisely-addressing-svc:8080
      - SUPPORTED_COUNTRIES_GEOCODE=usa,gbr,deu,aus,fra,can,mex,bra,arg,rus,ind,sgp,nzl,jpn,tgl,world
      - SUPPORTED_REGIONS_GEOCODE=amer,emea1,emea2,emea3,emea4,emea5,emea6,apac1,apac2
      - AUTH_ENABLED=false
    networks:
      - preciselyaddressing
    restart: always
  precisely-addressing-svc:
    image: ${_ADDRESSING_IMAGE:-addressing-service:latest}
    platform: linux/amd64
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 4G
    volumes:
      - ${_DATA_PATH:-/data/extracted}:/mnt/data/extracted
    environment:
      - DATA_PATH=/mnt/data/extracted
      - ENABLED_ENDPOINTS=${_ENABLED_API:-verify,geocode}
      - DATA_REGION=${_DATA_REGION:-USA}
    networks:
      - preciselyaddressing
    restart: always
networks:
  preciselyaddressing:
    name: geo-addressing