apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-sa"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
  labels:
    {{- include "reference-data.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-role"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-role-binding"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
    "helm.sh/resource-policy": delete
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-sa"
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-role"
  apiGroup: rbac.authorization.k8s.io