{{- if .Values.enabled }}
{{- if .Values.autoscaling.enabled }}
{{- $top := . -}}
{{- $country := "express" -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autocomplete-express.fullname" (list $top $country) }}
  labels:
    {{- include "autocomplete-express.labels" (list $top $country) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "autocomplete-express.fullname" (list $top $country) }}
  minReplicas: {{ $top.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $top.Values.autoscaling.maxReplicas }}
  metrics:
    {{- if $top.Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $top.Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}