{{- if .Values.enabled }}
{{- if .Values.serviceAccount.create -}}
{{- $top := . -}}
{{- $country := "express" -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "autocomplete-express.serviceAccountName" (list $top $country) }}
  labels:
    {{- include "autocomplete-express.labels" (list $top $country) | nindent 4 }}
  {{- with $top.Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
