nameOverride: "custom-data"
fullnameOverride: "custom-data"

nodeSelector: { }

serviceAccount:
  annotations: { }

dataImport:
  enabled: true
  image:
    repository: "custom-data-importer"
    pullPolicy: Always
    tag: 2.0.1
    pullSecrets: []
  config:
    expressUrl: "https://express-engine-cluster-master:9200"
    s3AccessKeyId: ""
    s3AccessKeySecret: ""
    s3Region: "us-east-1"
    csvSourceFile: "s3://new-bucket/data.csv"
