{{- if .Values.enabled }}
{{- $top := . -}}
{{- $country := "express" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "addressing-express.fullname" (list $top $country) }}
  labels:
    service: precisely
    app: {{ include "addressing-express.fullname" (list $top $country) }}
    {{- include "addressing-express.labels" (list $top $country) | nindent 4 }}
spec:
  {{- if not $top.Values.autoscaling.enabled }}
  replicas: {{ $top.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      service: precisely
      app: {{ include "addressing-express.fullname" (list $top $country) }}
      {{- include "addressing-express.selectorLabels" (list $top $country) | nindent 6 }}
  template:
    metadata:
      {{- with $top.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        service: precisely
        app: {{ include "addressing-express.fullname" (list $top $country) }}
        {{- include "addressing-express.selectorLabels" (list $top $country) | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 60
      {{- with $top.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "addressing-express.serviceAccountName" (list $top $country) }}
      securityContext:
        {{- toYaml $top.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $top.Chart.Name }}
          securityContext:
            {{- toYaml $top.Values.securityContext | nindent 12 }}
          image: "{{ $top.Values.global.addressingImage.repository }}:{{ $top.Values.global.addressingImage.tag | default $top.Chart.AppVersion }}"
          imagePullPolicy: {{ $top.Values.global.addressingImage.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            failureThreshold: 2
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            {{- toYaml $top.Values.resources | nindent 12 }}
          env:
            - name: AUTOCOMPLETE_V2_ENABLED
              value: "true"
            - name: GEOCODE_VERIFY_ENABLED
              value: "false"
            - name: LOOKUP_ENABLED
              value: "false"
            - name: REVERSEGEOCODE_ENABLED
              value: "false"
            - name: AUTOCOMPLETE_ENABLED
              value: "false"
            - name: COUNTRY_FINDER_ENABLED
              value: "true"
            - name: EXPRESS_URL
              value: "https://express-engine-cluster-master:9200"
            {{- if $top.Values.global.otelExporterEndpoint }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ $top.Values.global.otelExporterEndpoint }}
            {{- else }}
            - name: OTEL_TRACES_EXPORTER
              value: none
            {{- end }}
            - name: AUTH_ENABLED
              value: "false"
      {{- with ((get $top.Values "nodeSelector") | default ($top.Values.global)).nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $top.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}