{{- if .Values.enabled }}
{{- $top := . -}}
{{- $country := "express" -}}
{{- if $top.Values.maxUnavailable }}
---
{{- if semverCompare ">=1.21-0" $top.Capabilities.KubeVersion.GitVersion -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "addressing-express.fullname" (list $top $country) }}-pdb
  labels:
    {{- include "addressing-express.labels" (list $top $country) | nindent 4 }}
spec:
  maxUnavailable: {{ $top.Values.maxUnavailable }}
  selector:
    matchLabels:
      service: precisely
      app: {{ include "addressing-express.fullname" (list $top $country) }}
      {{- include "addressing-express.selectorLabels" (list $top $country) | nindent 6 }}
{{- end }}
{{- end }}