{{- if .Values.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "expressEngine.uname" . }}
  labels:
    {{- include "expressEngine.labels" . | nindent 4 }}
  annotations:
    majorVersion: "{{ include "expressEngine.majorVersion" . }}"
    {{- with .Values.expressEngineAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ template "expressEngine.serviceName" . }}-headless
  selector:
    matchLabels:
      {{- include "expressEngine.selectorLabels" . | nindent 6 }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  {{- if .Values.persistence.enabled }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  volumeClaimTemplates:
  - metadata:
      name: {{ template "expressEngine.uname" . }}
    {{- if .Values.persistence.labels.enabled }}
      labels:
        {{- include "expressEngine.labels" . | nindent 8 }}
    {{- end }}
    {{- with .Values.persistence.annotations  }}
      annotations:
{{ toYaml . | indent 8 }}
    {{- end }}
    spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
      - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{tpl .Values.persistence.storageClass . }}"
    {{- end }}
    {{- end }}
  {{- end }}
  template:
    metadata:
      name: "{{ template "expressEngine.uname" . }}"
      labels:
        {{- include "expressEngine.labels" . | nindent 8 }}
      annotations:
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- /* This forces a restart if the configmap has changed */}}
        {{- if .Values.config }}
        configchecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
        {{- if .Values.securityConfig.config.data }}
        securityconfigchecksum: {{ include (print .Template.BasePath "/securityconfig.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      {{- if .Values.schedulerName }}
      schedulerName: "{{ .Values.schedulerName }}"
      {{- end }}
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
        {{- if .Values.sysctl.enabled }}
        sysctls:
        - name: vm.max_map_count
          value: {{ .Values.sysctlVmMaxMapCount | quote }}
        {{- end }}
      automountServiceAccountToken: false
      {{- if .Values.imagePullSecrets }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- if or (eq .Values.antiAffinity "hard") (eq .Values.antiAffinity "soft") (eq .Values.antiAffinity "custom") .Values.nodeAffinity .Values.podAffinity }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      affinity:
      {{- end }}
      {{- if eq .Values.antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Release.Name }}
              - key: app.kubernetes.io/name
                operator: In
                values:
                - {{ include "expressEngine.name" . }}
            topologyKey: {{ .Values.antiAffinityTopologyKey }}
      {{- else if eq .Values.antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: {{ .Values.antiAffinityTopologyKey }}
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - {{ .Release.Name }}
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "expressEngine.name" . }}
      {{- else if eq .Values.antiAffinity "custom" }}
        {{- with .Values.customAntiAffinity }}
        podAntiAffinity:
{{ toYaml . | indent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.podAffinity }}
        podAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
        nodeAffinity:
{{ toYaml . | indent 10 }}
      {{- end }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriod }}
      volumes:
      {{- if .Values.config }}
      - name: config
        configMap:
          name: {{ template "expressEngine.uname" . }}-config
      {{- end }}
      {{- if and .Values.securityConfig.config.data .Values.securityConfig.config.securityConfigSecret }}
      {{ fail "Only one of .Values.securityConfig.config.data and .Values.securityConfig.config.securityConfigSecret may be defined. Please see the comment in values.yaml describing usage." }}
      {{- end }}
      {{- if .Values.securityConfig.config.data }}
      - name: security-config-data
        secret:
          secretName: {{ include "expressEngine.uname" . }}-securityconfig
      {{- end }}
      {{- with .Values.securityConfig.config.securityConfigSecret }}
      - name: security-config-complete
        secret:
          secretName: {{ . | quote }}
      {{- end }}
      {{- if .Values.securityConfig.actionGroupsSecret }}
      - name: action-groups
        secret:
          secretName: {{ .Values.securityConfig.actionGroupsSecret }}
      {{- end }}
      {{- if .Values.securityConfig.configSecret }}
      - name: security-config
        secret:
          secretName: {{ .Values.securityConfig.configSecret }}
      {{- end }}
      {{- if .Values.securityConfig.internalUsersSecret }}
      - name: internal-users-config
        secret:
          secretName: {{ .Values.securityConfig.internalUsersSecret }}
      {{- end }}
      {{- if .Values.securityConfig.rolesSecret }}
      - name: roles
        secret:
          secretName: {{ .Values.securityConfig.rolesSecret }}
      {{- end }}
      {{- if .Values.securityConfig.rolesMappingSecret }}
      - name: role-mapping
        secret:
          secretName: {{ .Values.securityConfig.rolesMappingSecret }}
      {{- end -}}
      {{- if .Values.securityConfig.tenantsSecret }}
      - name: tenants
        secret:
          secretName: {{ .Values.securityConfig.tenantsSecret }}
      {{- end }}
{{- if .Values.keystore }}
      - name: keystore
        emptyDir: {}
      {{- range .Values.keystore }}
      - name: keystore-{{ .secretName }}
        secret: {{ toYaml . | nindent 12 }}
      {{- end }}
{{ end }}
      {{- if .Values.extraVolumes }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraVolumes) }}
{{ tpl .Values.extraVolumes . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraVolumes | indent 6 }}
      {{- end }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- if or (.Values.extraInitContainers) (.Values.keystore) (.Values.persistence.enabled) (.Values.sysctlInit.enabled)  }}
      initContainers:
{{- if and .Values.persistence.enabled .Values.persistence.enableInitChown }}
      - name: fsgroup-volume
        image: "{{ .Values.persistence.image | default "busybox" }}:{{ .Values.persistence.imageTag | default "latest" }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command: ['sh', '-c']
        args:
          - {{- printf "chown -R %d:%d %s/data" (.Values.securityContext.runAsUser | int) (.Values.securityContext.runAsUser | int) .Values.expressEngineHome | quote | indent 1}}
        securityContext:
          runAsUser: 0
        resources:
          {{- toYaml .Values.initResources | nindent 10 }}
        volumeMounts:
          - name: "{{ template "expressEngine.uname" . }}"
            mountPath: {{ .Values.expressEngineHome }}/data
{{- end }}
{{- if .Values.sysctlInit.enabled }}
      - name: sysctl
        image: "{{ .Values.sysctlInit.image | default "busybox" }}:{{ .Values.sysctlInit.imageTag | default "latest" }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        command:
        - sh
        - -c
        - |
          set -xe
          DESIRED="{{ .Values.sysctlVmMaxMapCount }}"
          CURRENT=$(sysctl -n vm.max_map_count)
          if [ "$DESIRED" -gt "$CURRENT" ]; then
            sysctl -w vm.max_map_count=$DESIRED
          fi
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          {{- toYaml .Values.initResources | nindent 10 }}
{{- end }}
      {{- if .Values.extraInitContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
{{ tpl .Values.extraInitContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
      - name: "{{ template "expressEngine.name" . }}"
        securityContext:
{{ toYaml .Values.securityContext | indent 10 }}
        image: "{{ $top.Values.global.expressEngineImage.repository }}:{{ $top.Values.global.expressEngineImage.tag | default $top.Chart.AppVersion }}"
        imagePullPolicy: "{{ $top.Values.global.expressEngineImage.pullPolicy }}"
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
      {{- if semverCompare ">=1.16-0" .Capabilities.KubeVersion.Version }}
        startupProbe:
{{ toYaml .Values.startupProbe | indent 10 }}
      {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.httpPort }}
          {{- if .Values.httpHostPort }}
          hostPort: {{ .Values.httpHostPort }}
          {{- end }}
        - name: transport
          containerPort: {{ .Values.transportPort }}
          {{- if .Values.transportHostPort }}
          hostPort: {{ .Values.transportHostPort }}
          {{- end }}
        - name: metrics
          containerPort: {{ .Values.metricsPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- if ((has "master" .Values.roles)) }}
        - name: cluster.initial_master_nodes
          value: "{{ template "expressEngine.endpoints" . }}"
        {{- end }}
        - name: discovery.seed_hosts
          value: "{{ template "expressEngine.masterService" . }}-headless"
        - name: cluster.name
          value: "{{ .Values.clusterName }}"
        - name: network.host
          value: "{{ .Values.networkHost }}"
        - name: OPENSEARCH_JAVA_OPTS
          value: "{{ .Values.expressEngineJavaOpts }}"
        - name: node.roles
          value: "{{ template "expressEngine.roles" . }}"
{{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 8 }}
{{- end }}
{{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 8 }}
{{- end }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: "{{ template "expressEngine.uname" . }}"
          mountPath: {{ .Values.expressEngineHome }}/data
        {{- end }}
        {{- if .Values.securityConfig.enabled }}
        {{- if .Values.securityConfig.actionGroupsSecret }}
        - mountPath: {{ .Values.securityConfig.path }}/action_groups.yml
          name: action-groups
          subPath: action_groups.yml
        {{- end }}
        {{- if .Values.securityConfig.configSecret }}
        - mountPath: {{ .Values.securityConfig.path }}/config.yml
          name: security-config
          subPath: config.yml
        {{- end }}
        {{- if .Values.securityConfig.internalUsersSecret }}
        - mountPath: {{ .Values.securityConfig.path }}/internal_users.yml
          name: internal-users-config
          subPath: internal_users.yml
        {{- end }}
        {{- if .Values.securityConfig.rolesSecret }}
        - mountPath: {{ .Values.securityConfig.path }}/roles.yml
          name: roles
          subPath: roles.yml
        {{- end }}
        {{- if .Values.securityConfig.rolesMappingSecret }}
        - mountPath: {{ .Values.securityConfig.path }}/roles_mapping.yml
          name: role-mapping
          subPath: roles_mapping.yml
        {{- end }}
        {{- if .Values.securityConfig.tenantsSecret }}
        - mountPath: {{ .Values.securityConfig.path }}/tenants.yml
          name: tenants
          subPath: tenants.yml
        {{- end }}
        {{- if .Values.securityConfig.config.data }}
        {{-   if .Values.securityConfig.config.dataComplete }}
        - mountPath: {{ .Values.securityConfig.path }}
          name: security-config-data
        {{-   else }}
        {{-     range $key, $_ := .Values.securityConfig.config.data  }}
        - mountPath: {{ $.Values.securityConfig.path }}/{{ $key }}
          name: security-config-data
          subPath: {{ $key }}
        {{-     end }}
        {{-   end }}
        {{- else if .Values.securityConfig.config.securityConfigSecret }}
        - mountPath: {{ .Values.securityConfig.path }}
          name: security-config-complete
        {{- end }}
        {{- end }}
        {{- range $path, $config := .Values.config }}
        - name: config
          mountPath: {{ $.Values.expressEngineHome }}/config/{{ $path }}
          subPath: {{ $path }}
        {{- end -}}
        {{- if .Values.extraVolumeMounts }}
        # Currently some extra blocks accept strings
        # to continue with backwards compatibility this is being kept
        # whilst also allowing for yaml to be specified too.
        {{- if eq "string" (printf "%T" .Values.extraVolumeMounts) }}
{{ tpl .Values.extraVolumeMounts . | indent 8 }}
        {{- else }}
{{ toYaml .Values.extraVolumeMounts | indent 8 }}
        {{- end }}
        {{- end }}
      {{- if .Values.masterTerminationFix }}
      {{- if has "master" .Values.roles }}
      # This sidecar will prevent slow master re-election
      - name: expressEngine-master-graceful-termination-handler
        image: "{{ $top.Values.global.expressEngineImage.repository }}:{{ $top.Values.global.expressEngineImage.tag | default $top.Chart.AppVersion }}"
        imagePullPolicy: "{{ $top.Values.global.expressEngineImage.pullPolicy }}"
        command:
        - "sh"
        - -c
        - |
          #!/usr/bin/env bash
          set -eo pipefail

          http () {
              local path="${1}"
              if [ -n "${USERNAME}" ] && [ -n "${PASSWORD}" ]; then
                BASIC_AUTH="-u ${USERNAME}:${PASSWORD}"
              else
                BASIC_AUTH=''
              fi
              curl -XGET -s -k --fail ${BASIC_AUTH} {{ .Values.protocol }}://{{ template "expressEngine.masterService" . }}:{{ .Values.httpPort }}${path}
          }

          cleanup () {
            while true ; do
              local master="$(http "/_cat/master?h=node" || echo "")"
              if [[ $master == "{{ template "expressEngine.masterService" . }}"* && $master != "${NODE_NAME}" ]]; then
                echo "This node is not master."
                break
              fi
              echo "This node is still master, waiting gracefully for it to step down"
              sleep 1
            done

            exit 0
          }

          trap cleanup SIGTERM

          sleep infinity &
          wait $!
        resources:
          {{- toYaml .Values.sidecarResources | nindent 10 }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- if .Values.extraEnvs }}
{{ toYaml .Values.extraEnvs | indent 8 }}
        {{- end }}
        {{- if .Values.envFrom }}
        envFrom:
{{ toYaml .Values.envFrom | indent 8 }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.extraContainers }}
      # Currently some extra blocks accept strings
      # to continue with backwards compatibility this is being kept
      # whilst also allowing for yaml to be specified too.
      {{- if eq "string" (printf "%T" .Values.extraContainers) }}
{{ tpl .Values.extraContainers . | indent 6 }}
      {{- else }}
{{ toYaml .Values.extraContainers | indent 6 }}
      {{- end }}
      {{- end }}
{{- end }}
