apiVersion: v2
name: geo-addressing-eks
description: A Helm chart for Geo Addressing service

type: application
version: 4.0.0
appVersion: "1.16.0"
dependencies:
  - name: geo-addressing
    repository: file://../../component-charts/geo-addressing-generic
    version: "4.0.0"
  - name: nats
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    version: 1.2.*
    condition: geo-addressing.event-emitter.enabled