apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: geo-addressing
  region: us-east-1

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-efs-csi-driver

managedNodeGroups:
  - name: geo-addressing-worker
    instanceType: m5.2xlarge
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AutoScalingFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonElasticFileSystemFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy
      withAddonPolicies:
        externalDNS: true
        certManager: true
        imageBuilder: true
        ebs: true
        fsx: true
        efs: true
        appMesh: true
        xRay: true
        autoScaler: true
        albIngress: true
        cloudWatch: true
    minSize: 1
    maxSize: 10
    volumeSize: 200
    labels: { node-app: geo-addressing }
    tags:
      CreatedBy: Precisely

  - name: geo-addressing-ingress
    instanceType: m5.2xlarge
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AutoScalingFullAccess
      withAddonPolicies:
        externalDNS: true
        certManager: true
        imageBuilder: true
        ebs: true
        fsx: true
        efs: true
        appMesh: true
        xRay: true
        autoScaler: true
        albIngress: true
        cloudWatch: true
    desiredCapacity: 1
    labels: { node-app: geo-addressing-ingress }
    volumeSize: 50
    tags:
      CreatedBy: Precisely